### ISSUE TITLE
Example project is broken

### ISSUE THREAD

**Issue by subsoap** [astrochili/defold-trenchbroom#6]
![ex](https://user-images.githubusercontent.com/409170/192966803-556d9ea2-abe1-4597-ac4a-99ce1b03299f.png)

**Comment by subsoap** [comment]
![2](https://user-images.githubusercontent.com/409170/192968998-d406937c-722b-418c-8100-5f2e8fd3efd8.png)
running these on the included map makes the example work, should the extra files be included so example runs without needing to do this?

**Comment by astrochili** [comment]
The example is without the necessary files just to demonstrate how the process works, i.e. it's an opportunity to run the conversion yourself on the example.

Probably, this is not the best idea and it's necessary to include final files 🧐

**Comment by subsoap** [comment]
Maybe just some text higher up in the readme to explain they need to run the editor extension on the specific files before being able to run the example is needed?

**Comment by subsoap** [comment]
# Running the Example

To run the example project, you first need to run two editor extension functions on a map file provided. With the project open in Defold, right click on the [level.map](https://github.com/astrochili/defold-trenchbroom/blob/master/assets/maps/level/level.map) file then click on ```Prepare Map Components Folder```. This will create a variety of files next to the .map file. Next right click on the .map file and click ```Convert Map to Collection```. You can now run the example.

**Comment by astrochili** [comment]
Sounds great, I think I can rewrite some paragraphs with these statements.

**Comment by astrochili** [comment]
Finally updated the manual. Thanks for the text.
