### ISSUE TITLE
Can't convert map to collection due to Windows encoding

### ISSUE THREAD

**Issue by ReanimatorXP** [astrochili/defold-trenchbroom#8]
First of all, converting the map file distributing within the github project works fine. However, when I open the map file in Trenchbroom (on Windows 10), save it and re-export the .obj file without any changes - I got an issue with the map conversion proccess:
![image](https://user-images.githubusercontent.com/24944063/235640426-ee755ca1-bd34-4fc7-96af-39e1755235ec.png)
There is nothing special, it happens due to Windows encoding: the re-exported .obj file has CR/LF instead of just LF. So, I made a change in a regex pattern in the utils.get_lines funciton to :  `'[^\r\n]+`
```
function utils.get_lines(content)
...
  for line in content:gmatch '[^\r\n]+' do
    table.insert(lines, line)
  end
...
```
And now it works with both the CR/LF and LF line endings, on Mac and Windows.
Maybe it can help.

**Comment by astrochili** [comment]
Thanks you! Fixed.
